---
app_container_name: devops-example-app
app_image: voitov/devops-example-app:latest
app_port: 8080

domain_name: voitov.online
certbot_email: admin@voitov.online

datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_app_key: "{{ vault_datadog_app_key }}"
datadog_site: datadoghq.eu
datadog_agent_major_version: 7

yc_token: "{{ vault_yc_token }}"
yc_cloud_id: "{{ vault_yc_cloud_id }}"
yc_folder_id: "{{ vault_yc_folder_id }}"

db_password: "{{ vault_db_password }}"
